# common variables
availability_zone: melbourne-qh2-uom

# security group
security_groups:
  - name: instance_ssh
    description: "security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: instance_http
    description: "security group for HTTP access"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: instance_couchdb
    description: "security group for couchdb cluster setup"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0

# instance openstacksdk
instance0_name: instance0
instance1_name: instance1
instance2_name: instance2
instance3_name: instance3
instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: key
instance_flavor: uom.mse.2c9g
instance_network: qh2-uom-internal

# couchdb user and password
username: admin
password: 123456

#proxy
proxy_address: http://wwwproxy.unimelb.edu.au:8000
