# render the templates

- name: output the IP to inventory file
  vars:
    instance0_ip: "{{ os_instance0.openstack.public_v4 }}"
    instance1_ip: "{{ os_instance1.openstack.public_v4 }}"
    instance2_ip: "{{ os_instance2.openstack.public_v4 }}"
    instance3_ip: "{{ os_instance3.openstack.public_v4 }}"
  template:
    src: inventory.ini.j2
    dest: ./inventory.ini

- name: output the IP to the masternode bash script
  vars:
    instance0_ip: "{{ os_instance0.openstack.public_v4 }}"
    instance1_ip: "{{ os_instance1.openstack.public_v4 }}"
    instance2_ip: "{{ os_instance2.openstack.public_v4 }}"
    instance3_ip: "{{ os_instance3.openstack.public_v4 }}"
  template:
    src: masternode.sh.j2
    dest: ./roles/couchdb-masternode/tasks/masternode.sh

- name: output the IP to the subnode1 bash script
  vars:
    instance1_ip: "{{ os_instance1.openstack.public_v4 }}"
  template:
    src: subnode1.sh.j2
    dest: ./roles/couchdb-subnode1/tasks/subnode1.sh

- name: output the IP to the subnode2 bash script
  vars:
    instance2_ip: "{{ os_instance2.openstack.public_v4 }}"
  template:
    src: subnode2.sh.j2
    dest: ./roles/couchdb-subnode2/tasks/subnode2.sh

- name: output the IP to the subnode3 bash script
  vars:
    instance3_ip: "{{ os_instance3.openstack.public_v4 }}"
  template:
    src: subnode3.sh.j2
    dest: ./roles/couchdb-subnode3/tasks/subnode3.sh

- name: output the IP to the data-populate bash script
  vars:
    instance0_ip: "{{ os_instance0.openstack.public_v4 }}"
  template:
    src: data-populate.sh.j2
    dest: ./roles/background-configuration/tasks/data-populate.sh